import streamlit as st
import pandas as pd
import os
import time
from visualization.utils import apply_lbg_theme, make_api_request, render_section_header, render_alert_banner

st.set_page_config(page_title="System Administration - GraphShield AI", layout="wide")
apply_lbg_theme()

st.markdown('# <span class="gradient-text">⚙️ System Administration</span>', unsafe_allow_html=True)
st.markdown('<div style="font-size: 1.05rem; font-weight: 500; color: #94A3B8; margin-top: -0.6rem; margin-bottom: 1.5rem;">Pipeline Monitoring, Retraining Control Board & batch Ingestion</div>', unsafe_allow_html=True)

# Grid panels: MLOps scheduler & Ingestion Batch uploader
col_left, col_right = st.columns([1, 1])

with col_left:
    with st.container(border=True):
        render_section_header("MLOps GNN Retraining Control Console", "Trigger weights recalibration on GPU nodes", "🚀")
        render_alert_banner(
            title="Relational Weights Recalibration",
            message="Executing GNN Retraining initiates a background subprocess utilizing PyTorch Geometric SAGEConvs. This optimizes node representation vectors based on new transactions and device sharing topologies.",
            alert_type="warning"
        )
        
        if st.button("🚀 Trigger GNN Weights Optimization", type="primary", use_container_width=True):
            with st.spinner("Spawning retraining process..."):
                res = make_api_request("POST", "/prediction/train")
                if res:
                    st.success("🟢 Optimization job initiated successfully!")
                    st.json(res)

with col_right:
    with st.container(border=True):
        render_section_header("Batch Transaction CSV Ingestion", "Upload batch files to run pipeline validation logs", "📥")
        uploaded_file = st.file_uploader("Upload Batch CSV File:", type=["csv"])
        
        if uploaded_file is not None:
            with st.spinner("Processing ingestion validation check..."):
                progress_bar = st.progress(0)
                try:
                    df = pd.read_csv(uploaded_file)
                    time.sleep(0.3)
                    progress_bar.progress(30)
                    
                    required = {"transaction_id", "sender_account_id", "receiver_account_id", "amount"}
                    missing = required - set(df.columns)
                    time.sleep(0.3)
                    progress_bar.progress(70)
                    
                    duplicates = df["transaction_id"].duplicated().sum() if "transaction_id" in df.columns else 0
                    time.sleep(0.2)
                    progress_bar.progress(100)
                    
                    st.markdown("---")
                    st.markdown("#### Ingestion Validation Log:")
                    
                    has_error = False
                    if not missing:
                        st.success("✅ **Check 1: Schema columns verification passed.**")
                    else:
                        st.error(f"❌ **Check 1: Schema check failed. Missing columns: {missing}**")
                        has_error = True
                        
                    if duplicates == 0:
                        st.success("✅ **Check 2: Primary Key uniqueness verified.**")
                    else:
                        st.error(f"❌ **Check 2: PK uniqueness failed. Duplicates found: {duplicates}**")
                        has_error = True
                        
                    if not has_error:
                        st.success("🎉 **Pipeline Validation: SUCCESS**. Batch ledger is healthy.")
                        st.dataframe(df.head(5), use_container_width=True)
                    else:
                        st.error("❌ **Pipeline Validation: FAILED**. Resolve errors before database commit.")
                except Exception as e:
                    st.error(f"Failed to read CSV batch: {str(e)}")

st.markdown("<div style='margin-bottom: 1.25rem;'></div>", unsafe_allow_html=True)

# Bottom Row: Database Referential Integrity Report
with st.container(border=True):
    render_section_header("Database Referential Integrity Report", "Validation records generated by automated pipeline modules", "📋")
    
    report_path = "d:/fraud_detection/docs/Data_Quality_Report.md"
    if os.path.exists(report_path):
        try:
            with open(report_path, "r", encoding="utf-8") as f:
                report_content = f.read()
            st.markdown(report_content)
        except Exception as e:
            st.error(f"Error loading validation report: {str(e)}")
    else:
        st.warning("Data quality validation report Data_Quality_Report.md was not found in the documents registry.")
